"""Configuration and parameter management"""

# Legacy flat parameters (now loaded from TOML for compatibility)
from .parameters import Parameters, read_params

# New Pydantic-based schema (recommended for new code)
from .schema import (
    Parameters as ParametersV2,
    load_parameters,
    # Enums
    ParallelMode,
    DetectEngine,
    BkgEdgeMethod,
    BkgMethod,
    MagFluxMode,
    ApertureMode,
    CacheStrategy,
    # Sub-configs
    IOConfig,
    TargetConfig,
    ParallelConfig,
    UIConfig,
    InstrumentConfig,
    AlignmentConfig,
    FWHMConfig,
    DetectionConfig,
    DeblendConfig,
    PeakConfig,
    DAOConfig,
    Background2DConfig,
    ClipConfig,
    QCConfig,
    PhotConfig,
    ApertureScalesConfig,
    ApertureRadiiConfig,
    ApcorrConfig,
    WCSConfig,
    WCSRefineConfig,
    GAIAConfig,
    IDMatchConfig,
    MasterCatalogConfig,
    MasterEditorConfig,
    MatchConfig,
    CMDConfig,
    ZPConfig,
    ColorConfig,
    IsochroneConfig,
    OverlayConfig,
    HUD5XConfig,
    TransformConfig,
)

__all__ = [
    # Main classes
    'Parameters',           # Legacy flat (TOML-based) - default
    'ParametersV2',         # New Pydantic (toml-based)
    'load_parameters',
    'read_params',
    # Enums
    'ParallelMode',
    'DetectEngine',
    'BkgEdgeMethod',
    'BkgMethod',
    'MagFluxMode',
    'ApertureMode',
    'CacheStrategy',
    # Sub-configs
    'IOConfig',
    'TargetConfig',
    'ParallelConfig',
    'UIConfig',
    'InstrumentConfig',
    'AlignmentConfig',
    'FWHMConfig',
    'DetectionConfig',
    'DeblendConfig',
    'PeakConfig',
    'DAOConfig',
    'Background2DConfig',
    'ClipConfig',
    'QCConfig',
    'PhotConfig',
    'ApertureScalesConfig',
    'ApertureRadiiConfig',
    'ApcorrConfig',
    'WCSConfig',
    'WCSRefineConfig',
    'GAIAConfig',
    'IDMatchConfig',
    'MasterCatalogConfig',
    'MasterEditorConfig',
    'MatchConfig',
    'CMDConfig',
    'ZPConfig',
    'ColorConfig',
    'IsochroneConfig',
    'OverlayConfig',
    'HUD5XConfig',
    'TransformConfig',
]
